# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Personal Inventory's Docs
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
